name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['0.[0-9]+.[0-9]+']


jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compilation
        run: pnpm run compile

      - name: Test conversion
        run: pnpm run test

      - name: Code Style
        run: pnpm run lint

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
