name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Compilation
        run: npm run compile
      - name: Code Style
        run: npm run lint
